### ISSUE TITLE
Add site title and description to Markdown lesson

### ISSUE THREAD

**Issue by egillespie** [humanitycodes/codelab#283]
Introduce the `title` and `description` fields to `_config.yml` to show how the theme title can be overridden. Also, add a requirement to set a site title for the project.

Sample `_config.yml`:

``` yaml
theme: jekyll-theme-cayman
title: "My next big project"
description: "Hint: it's all about Markdown"
```
